services:
  db:
    image: postgres:16-alpine
    container_name: logitrack-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-logitrack}
      POSTGRES_USER: ${POSTGRES_USER:-logitrack}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-logitrack}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-logitrack} -d ${POSTGRES_DB:-logitrack}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend

    container_name: logitrack-api
    restart: unless-stopped

    environment:
      SERVER_PORT: 8080

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-logitrack}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-logitrack}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-logitrack}

      LOGITRACK_JWT_SECRET: ${LOGITRACK_JWT_SECRET:-LogiTrackDockerJwtSecretKeyWithAtLeastThirtyTwoCharacters2026}

      LOGITRACK_ALLOWED_ORIGINS: ${LOGITRACK_ALLOWED_ORIGINS:-https://gestaoentregas.duckdns.org}

    ports:
      - "127.0.0.1:18080:8080"

    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api

    container_name: logitrack-web
    restart: unless-stopped

    ports:
      - "127.0.0.1:3001:80"

    depends_on:
      - backend

volumes:
  postgres_data: