-- Idempotent baseline for both fresh installations and databases previously
-- managed by Hibernate ddl-auto=update. Flyway is baselined at version 0.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS drivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    license_number VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(40) NOT NULL,
    current_vehicle VARCHAR(255),
    deliveries_completed INTEGER NOT NULL DEFAULT 0,
    success_rate NUMERIC(5,2) NOT NULL DEFAULT 100
);

CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate VARCHAR(12) NOT NULL UNIQUE,
    model VARCHAR(255) NOT NULL,
    capacity_kg NUMERIC(10,2) NOT NULL,
    status VARCHAR(40) NOT NULL,
    linked_driver_id BIGINT REFERENCES drivers(id)
);

CREATE TABLE IF NOT EXISTS route_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    origin VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    estimated_distance_km NUMERIC(8,2) NOT NULL,
    estimated_time_minutes INTEGER NOT NULL,
    status VARCHAR(40) NOT NULL,
    origin_lat DOUBLE PRECISION NOT NULL,
    origin_lng DOUBLE PRECISION NOT NULL,
    destination_lat DOUBLE PRECISION NOT NULL,
    destination_lng DOUBLE PRECISION NOT NULL,
    color VARCHAR(16) NOT NULL
);

CREATE TABLE IF NOT EXISTS delivery_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(32) NOT NULL UNIQUE,
    tracking_code VARCHAR(40) NOT NULL UNIQUE,
    customer_name VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(2) NOT NULL,
    order_value NUMERIC(12,2) NOT NULL,
    weight_kg NUMERIC(10,2) NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expected_delivery_at TIMESTAMP NOT NULL
);

ALTER TABLE delivery_orders ADD COLUMN IF NOT EXISTS tracking_code VARCHAR(40);
ALTER TABLE delivery_orders ADD COLUMN IF NOT EXISTS weight_kg NUMERIC(10,2) DEFAULT 0;
UPDATE delivery_orders SET tracking_code = 'LT-LEGACY-' || LPAD(id::text, 12, '0')
WHERE tracking_code IS NULL OR tracking_code = '';
UPDATE delivery_orders SET weight_kg = 0 WHERE weight_kg IS NULL;
ALTER TABLE delivery_orders ALTER COLUMN tracking_code SET NOT NULL;
ALTER TABLE delivery_orders ALTER COLUMN weight_kg SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_orders_tracking_code ON delivery_orders(tracking_code);

CREATE TABLE IF NOT EXISTS deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    order_id BIGINT NOT NULL REFERENCES delivery_orders(id),
    driver_id BIGINT NOT NULL REFERENCES drivers(id),
    vehicle_id BIGINT NOT NULL REFERENCES vehicles(id),
    route_id BIGINT REFERENCES route_plans(id),
    origin VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    expected_at TIMESTAMP NOT NULL,
    delivered_at TIMESTAMP,
    status VARCHAR(40) NOT NULL,
    progress INTEGER NOT NULL,
    current_lat DOUBLE PRECISION NOT NULL,
    current_lng DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL
);

ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
UPDATE deliveries SET version = 0 WHERE version IS NULL;
ALTER TABLE deliveries ALTER COLUMN version SET NOT NULL;

CREATE TABLE IF NOT EXISTS delivery_timelines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id BIGINT NOT NULL REFERENCES deliveries(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    status VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id BIGINT REFERENCES deliveries(id),
    order_id BIGINT REFERENCES delivery_orders(id),
    type VARCHAR(60) NOT NULL,
    priority VARCHAR(30) NOT NULL,
    status VARCHAR(40) NOT NULL,
    responsible VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    resolution VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Databases created by the former Hibernate ddl-auto=update strategy contain
-- enum CHECK constraints generated from the enum values that existed at that
-- time. Replace those constraints before normalizing legacy values so the
-- migration works for both existing installations and clean databases.
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE drivers DROP CONSTRAINT IF EXISTS drivers_status_check;
ALTER TABLE vehicles DROP CONSTRAINT IF EXISTS vehicles_status_check;
ALTER TABLE route_plans DROP CONSTRAINT IF EXISTS route_plans_status_check;
ALTER TABLE delivery_orders DROP CONSTRAINT IF EXISTS delivery_orders_status_check;
ALTER TABLE deliveries DROP CONSTRAINT IF EXISTS deliveries_status_check;
ALTER TABLE delivery_timelines DROP CONSTRAINT IF EXISTS delivery_timelines_status_check;
ALTER TABLE incidents DROP CONSTRAINT IF EXISTS incidents_type_check;
ALTER TABLE incidents DROP CONSTRAINT IF EXISTS incidents_priority_check;
ALTER TABLE incidents DROP CONSTRAINT IF EXISTS incidents_status_check;

ALTER TABLE users DROP CONSTRAINT IF EXISTS ck_users_role;
ALTER TABLE drivers DROP CONSTRAINT IF EXISTS ck_drivers_status;
ALTER TABLE vehicles DROP CONSTRAINT IF EXISTS ck_vehicles_status;
ALTER TABLE route_plans DROP CONSTRAINT IF EXISTS ck_routes_status;
ALTER TABLE delivery_orders DROP CONSTRAINT IF EXISTS ck_orders_status;
ALTER TABLE deliveries DROP CONSTRAINT IF EXISTS ck_deliveries_status;
ALTER TABLE delivery_timelines DROP CONSTRAINT IF EXISTS ck_timeline_status;
ALTER TABLE incidents DROP CONSTRAINT IF EXISTS ck_incidents_type;
ALTER TABLE incidents DROP CONSTRAINT IF EXISTS ck_incidents_priority;
ALTER TABLE incidents DROP CONSTRAINT IF EXISTS ck_incidents_status;

UPDATE incidents SET type = 'OTHER' WHERE type = 'PROBLEM_SOLVED';

ALTER TABLE users ADD CONSTRAINT ck_users_role CHECK
    (role IN ('ADMIN', 'OPERATOR', 'MONITORING', 'FLEET_MANAGER', 'DRIVER', 'VIEWER'));
ALTER TABLE drivers ADD CONSTRAINT ck_drivers_status CHECK
    (status IN ('AVAILABLE', 'ON_ROUTE', 'UNAVAILABLE', 'INACTIVE'));
ALTER TABLE vehicles ADD CONSTRAINT ck_vehicles_status CHECK
    (status IN ('AVAILABLE', 'ON_ROUTE', 'MAINTENANCE', 'INACTIVE'));
ALTER TABLE route_plans ADD CONSTRAINT ck_routes_status CHECK
    (status IN ('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELED'));
ALTER TABLE delivery_orders ADD CONSTRAINT ck_orders_status CHECK
    (status IN ('PENDING', 'PICKING', 'COLLECTING', 'ON_THE_WAY', 'DELIVERED', 'DELAYED', 'CANCELED'));
ALTER TABLE deliveries ADD CONSTRAINT ck_deliveries_status CHECK
    (status IN ('IN_PROGRESS', 'COLLECTING', 'ON_THE_WAY', 'DELIVERED', 'DELAYED', 'CANCELED'));
ALTER TABLE delivery_timelines ADD CONSTRAINT ck_timeline_status CHECK
    (status IN ('IN_PROGRESS', 'COLLECTING', 'ON_THE_WAY', 'DELIVERED', 'DELAYED', 'CANCELED'));
ALTER TABLE incidents ADD CONSTRAINT ck_incidents_type CHECK
    (type IN ('DELIVERY_DELAY', 'CUSTOMER_NOT_FOUND', 'WRONG_ADDRESS', 'VEHICLE_PROBLEM',
              'DAMAGED_PRODUCT', 'REFUSED_DELIVERY', 'ACCIDENT', 'THEFT_OR_LOSS',
              'DOCUMENTATION_FAILURE', 'DRIVER_UNAVAILABLE', 'OTHER'));
ALTER TABLE incidents ADD CONSTRAINT ck_incidents_priority CHECK
    (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'));
ALTER TABLE incidents ADD CONSTRAINT ck_incidents_status CHECK
    (status IN ('OPEN', 'IN_REVIEW', 'IN_TREATMENT', 'WAITING_THIRD_PARTY', 'RESOLVED', 'CANCELED'));

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(64) NOT NULL,
    title VARCHAR(160) NOT NULL,
    message VARCHAR(500) NOT NULL,
    entity_type VARCHAR(40),
    entity_id BIGINT,
    path VARCHAR(240),
    read_at TIMESTAMP,
    deduplication_key VARCHAR(180) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_name VARCHAR(120) NOT NULL,
    participant_role VARCHAR(80) NOT NULL,
    context_type VARCHAR(40),
    context_id BIGINT,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS conversation_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_name VARCHAR(120) NOT NULL,
    sender_role VARCHAR(80) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    read_message BOOLEAN NOT NULL DEFAULT FALSE,
    attachment_type VARCHAR(32),
    attachment_id BIGINT,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(60) NOT NULL,
    entity_id BIGINT,
    actor VARCHAR(180) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_status ON delivery_orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON delivery_orders(created_at);
CREATE INDEX IF NOT EXISTS idx_orders_expected_at ON delivery_orders(expected_delivery_at);
CREATE INDEX IF NOT EXISTS idx_deliveries_status ON deliveries(status);
CREATE INDEX IF NOT EXISTS idx_deliveries_expected_at ON deliveries(expected_at);
CREATE INDEX IF NOT EXISTS idx_deliveries_order ON deliveries(order_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_driver ON deliveries(driver_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_vehicle ON deliveries(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_route ON deliveries(route_id);
CREATE INDEX IF NOT EXISTS idx_timeline_delivery_time ON delivery_timelines(delivery_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents(status);
CREATE INDEX IF NOT EXISTS idx_incidents_priority ON incidents(priority);
CREATE INDEX IF NOT EXISTS idx_incidents_created_at ON incidents(created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_read_at ON notifications(read_at);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_created ON conversation_messages(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_created_at ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs(entity_type, entity_id);
